# Generated by Django 4.2.21 on 2025-09-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to='songs/')),
            ],
        ),
    ]
