# Generated by Django 4.2.21 on 2025-09-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyric',
            field=models.TextField(blank=True, null=True),
        ),
    ]
