# Generated by Django 4.2.21 on 2025-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_song_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lrc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
