# Generated by Django 4.2.21 on 2025-09-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_song_lrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyric',
        ),
    ]
